name: Create Pull Request

on:
  push:
    branches:
      - development

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: 'master'
      
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: master 
          source_branch: development 
          pr_title: "feat: PLACEHOLDER TITLE"
          pr_body: 'Please pull these awesome changes in!'
          pr_reviewer: "kudgar"
          pr_label: 'automated-pr'
